version: "3.8"

services:
  blue_app:
    image: yimikaade/wonderful:devops-stage-two
    container_name: blue_app
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/version"]
      interval: 10s
      timeout: 3s
      retries: 3

  green_app:
    image: yimikaade/wonderful:devops-stage-two
    container_name: green_app
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/version"]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf:ro
      - ./logs/access.log:/var/log/nginx/access.log
      - ./logs/error.log:/var/log/nginx/error.log
    depends_on:
      - blue_app
      - green_app

  alert_watcher:
    build:
      context: ./watcher
      dockerfile: Dockerfile
    container_name: alert_watcher
    env_file: .env
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - ERROR_RATE_THRESHOLD=${ERROR_RATE_THRESHOLD}
      - WINDOW_SIZE=${WINDOW_SIZE}
      - ALERT_COOLDOWN_SEC=${ALERT_COOLDOWN_SEC}
      - LOG_PATH=${LOG_PATH}
    volumes:
      - ./logs/access.log:/var/log/nginx/access.log
    depends_on:
      - nginx_proxy

volumes:
  nginx_logs:


